sudo: false
language: python
python:
    - "2.7"
    - "3.6"
install: pip install coverage python-coveralls pytest pytest-flakes pytest-cov pytest-random
script:
    - python setup.py develop
    - pytest wlmodem
    - coverage run -m pytest wlmodem
    - coverage report -m --include "wlmodem/*"
after_success:
  - coveralls
