sudo: false
language: python
python:
    - "2.7"
    - "3.6"
install: pip install coverage pytest pytest-flakes pytest-cov pytest-random
script:
    - python setup.py develop
    - pytest wlmodem
    - coverage run -m pytest wlmodem
    - coverage report -m
after_success:
  - coveralls
