sudo: false
language: python
python:
    - "2.7"
    - "3.6"
install: pip install tox-travis coverage
script:
    - tox
    - coverage run -m pytest wlmodem
    - coverage -m
after_success:
  - coveralls
